jenkins:
    image: opreaadrian/jenkins
    volumes:
        - jenkins-items:/var/jenkins_home
        - .:/var/jenkins_data
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
    ports:
        - "8081:8080"
registry:
    image: registry
    environment:
        - STORAGE_PATH=/registry
    volumes:
        - registry-items:/registry
    ports:
        - "5000:5000"
